-- MariaDB schema for the Enterprise Database Server database 1-PERSONNEL
-- Compiled from ../samples/1-personnel.dasdl by DASDL, generated by model2sql.
--
-- Every table carries `rsn`: DMSII addresses a record by its
-- record serial number, and a relational row needs a key of
-- its own for the sets that reach it to point at something.
--
-- A set is an index over its data set; a subset is a table of
-- its own, because it holds entries for only some of the
-- records and an index cannot leave rows out. Reading whole
-- records through a subset is a join on `rsn`; reading only
-- its keys and DATA items — a FIND KEY OF — never leaves it.

CREATE DATABASE IF NOT EXISTS `1_personnel` DEFAULT CHARACTER SET utf8mb4;
USE `1_personnel`;

-- PERSONNEL (data set)
CREATE TABLE IF NOT EXISTS `personnel` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(30),
  `employee_no` DECIMAL(6,0) UNSIGNED,
  `department` CHAR(20),
  `phone` DECIMAL(10,0) UNSIGNED,
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

