-- MariaDB schema for the Enterprise Database Server database 3-OPTIONS
-- Compiled from ../samples/3-options.dasdl by DASDL, generated by model2sql.
--
-- Every table carries `rsn`, a key of its own. DMSII addresses
-- a record by its physical address — the AAWORD, which encodes
-- the block and the offset within it — and a relational row
-- needs a key that does not move when the record does, for the
-- sets that reach it to point at something.
--
-- A set is an index over its data set; a subset is a table of
-- its own, because it holds entries for only some of the
-- records and an index cannot leave rows out. Reading whole
-- records through a subset is a join on `rsn`; reading only
-- its keys and DATA items — a FIND KEY OF — never leaves it.

CREATE DATABASE IF NOT EXISTS `3_options` DEFAULT CHARACTER SET utf8mb4;
USE `3_options`;

-- The database's global items: one record for the whole
-- database, so one row, held down by a fixed key.
CREATE TABLE IF NOT EXISTS `dmsii_globals` (
  `rsn` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `pop_of_personnel` BIGINT UNSIGNED,
  PRIMARY KEY (`rsn`),
  CHECK (`rsn` = 1)
) ENGINE=InnoDB;

-- PERSONNEL (data set)
CREATE TABLE IF NOT EXISTS `personnel` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(30),
  `employee_no` DECIMAL(6,0) UNSIGNED,
  `department` CHAR(20),
  `phone` DECIMAL(10,0) UNSIGNED,
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

