-- MariaDB schema for the Enterprise Database Server database 4-PHYSICAL
-- Compiled from ../samples/4-physical.dasdl by DASDL, generated by model2sql.
--
-- Every table carries `rsn`, a key of its own. DMSII addresses
-- a record by its physical address — the AAWORD, which encodes
-- the block and the offset within it — and a relational row
-- needs a key that does not move when the record does, for the
-- sets that reach it to point at something.
--
-- A set is an index over its data set; a subset is a table of
-- its own, because it holds entries for only some of the
-- records and an index cannot leave rows out. Reading whole
-- records through a subset is a join on `rsn`; reading only
-- its keys and DATA items — a FIND KEY OF — never leaves it.

CREATE DATABASE IF NOT EXISTS `4_physical` DEFAULT CHARACTER SET utf8mb4;
USE `4_physical`;

-- RESTARTDS (restart data set)
CREATE TABLE IF NOT EXISTS `restartds` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `r_programname` CHAR(25),
  `r_userinfo` CHAR(250),
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- PERSONNEL (data set)
CREATE TABLE IF NOT EXISTS `personnel` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(30),
  `employee_no` DECIMAL(6,0) UNSIGNED,
  `department` CHAR(20),
  `phone` DECIMAL(10,0) UNSIGNED,
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- Sets and Accesses: an entry for every record of the data
-- set, which is what an index is.
CREATE UNIQUE INDEX `find_by_name` ON `personnel` (`name`);
CREATE UNIQUE INDEX `find_by_number` ON `personnel` (`employee_no`);

