-- MariaDB schema for the Enterprise Database Server database 6-REMAPS
-- Compiled from ../samples/6-remaps.dasdl by DASDL, generated by model2sql.
--
-- Every table carries `rsn`, a key of its own. DMSII addresses
-- a record by its physical address — the AAWORD, which encodes
-- the block and the offset within it — and a relational row
-- needs a key that does not move when the record does, for the
-- sets that reach it to point at something.
--
-- A set is an index over its data set; a subset is a table of
-- its own, because it holds entries for only some of the
-- records and an index cannot leave rows out. Reading whole
-- records through a subset is a join on `rsn`; reading only
-- its keys and DATA items — a FIND KEY OF — never leaves it.

CREATE DATABASE IF NOT EXISTS `6_remaps` DEFAULT CHARACTER SET utf8mb4;
USE `6_remaps`;

-- D (data set)
CREATE TABLE IF NOT EXISTS `d` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `a` CHAR(5),
  `b` BOOLEAN,
  `f` BIT(15),
  `g_g1` CHAR(2),
  `g_g2` DOUBLE,
  `n` DECIMAL(5,2),
  `p` DOUBLE,
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- CUST (data set)
CREATE TABLE IF NOT EXISTS `cust` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(20),
  `billing_addr_street` CHAR(20),
  `billing_addr_city` CHAR(15),
  `billing_addr_zip` DECIMAL(9,0) UNSIGNED,
  `cust_info_contract_no` DECIMAL(9,0) UNSIGNED,
  `cust_info_liaison` CHAR(20),
  `cust_info_phone` CHAR(10),
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- EMP (data set)
CREATE TABLE IF NOT EXISTS `emp` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rsn_item` DECIMAL(4,0) UNSIGNED,
  `last_name` CHAR(20),
  `first_name` CHAR(15),
  `salary` DOUBLE,
  `hourly` BOOLEAN,
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- Remaps: a second description of a record, which is a view
-- of the table the record is in.
CREATE OR REPLACE VIEW `r` AS
  SELECT `rsn`,
         `a`,
         `f`,
         `b`,
         `g_g2` AS `g2`,
         `n`
    FROM `d`
   WHERE `n` >= 1.0
  ;
  -- VERIFY N GEQ 1.0 (a store-time condition, not a view predicate)
CREATE OR REPLACE VIEW `customer` AS
  SELECT `rsn`,
         `name`,
         `cust_info_contract_no` AS `contract_no`,
         `cust_info_liaison` AS `liaison`,
         `cust_info_phone` AS `phone`,
         `billing_addr_street` AS `street`,
         `billing_addr_city` AS `city`,
         `billing_addr_zip` AS `zip`
    FROM `cust`
  ;
CREATE OR REPLACE VIEW `emp_view` AS
  SELECT `rsn`,
         `rsn_item`,
         `last_name`,
         `first_name`,
         NULL AS `initials`,
         (2 * `rsn_item`) AS `doubled`,
         (NOT `hourly`) AS `salaried`,
         NULL AS `flags`,
         (`last_name`) AS `short_name`
    FROM `emp`
  ;

