-- MariaDB schema for the Enterprise Database Server database 7-LOGICAL-DATABASE
-- Compiled from ../samples/7-logical-database.dasdl by DASDL, generated by model2sql.
--
-- Every table carries `rsn`, a key of its own. DMSII addresses
-- a record by its physical address — the AAWORD, which encodes
-- the block and the offset within it — and a relational row
-- needs a key that does not move when the record does, for the
-- sets that reach it to point at something.
--
-- A set is an index over its data set; a subset is a table of
-- its own, because it holds entries for only some of the
-- records and an index cannot leave rows out. Reading whole
-- records through a subset is a join on `rsn`; reading only
-- its keys and DATA items — a FIND KEY OF — never leaves it.

CREATE DATABASE IF NOT EXISTS `7_logical_database` DEFAULT CHARACTER SET utf8mb4;
USE `7_logical_database`;

-- The database's global items: one record for the whole
-- database, so one row, held down by a fixed key.
CREATE TABLE IF NOT EXISTS `dmsii_globals` (
  `rsn` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `g1` CHAR(10),
  `g2` DECIMAL(9,2),
  `g3` DOUBLE,
  PRIMARY KEY (`rsn`),
  CHECK (`rsn` = 1)
) ENGINE=InnoDB;

-- RDS (restart data set)
CREATE TABLE IF NOT EXISTS `rds` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rds_data` CHAR(30),
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- D (data set)
CREATE TABLE IF NOT EXISTS `d` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `d1` CHAR(5),
  `d2` DOUBLE,
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- E (data set), embedded in D
CREATE TABLE IF NOT EXISTS `d_e` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_rsn` BIGINT UNSIGNED NOT NULL,
  `e1` DECIMAL(4,0) UNSIGNED,
  `e2` BIT(8),
  PRIMARY KEY (`rsn`),
  KEY `d_e_parent` (`parent_rsn`),
  CONSTRAINT `d_e_owner` FOREIGN KEY (`parent_rsn`) REFERENCES `d` (`rsn`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- X-D1 (data set)
CREATE TABLE IF NOT EXISTS `x_d1` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `a` DOUBLE,
  `b` DECIMAL(5,0) UNSIGNED,
  `c` CHAR(5),
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- X-D2 (data set)
CREATE TABLE IF NOT EXISTS `x_d2` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `x` BIT(8),
  `y` CHAR(5),
  `z_z1` BOOLEAN,
  `z_z2` BOOLEAN,
  `z_z3` BOOLEAN,
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- XE (data set), embedded in X-D2
CREATE TABLE IF NOT EXISTS `x_d2_xe` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_rsn` BIGINT UNSIGNED NOT NULL,
  `k` DOUBLE,
  `m` BIT(14),
  PRIMARY KEY (`rsn`),
  KEY `x_d2_xe_parent` (`parent_rsn`),
  CONSTRAINT `x_d2_xe_owner` FOREIGN KEY (`parent_rsn`) REFERENCES `x_d2` (`rsn`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Sets and Accesses: an entry for every record of the data
-- set, which is what an index is.
CREATE UNIQUE INDEX `s_e` ON `d_e` (`parent_rsn`, `e1`);
CREATE UNIQUE INDEX `s_d` ON `d` (`d1`);
CREATE UNIQUE INDEX `s1a` ON `x_d1` (`a`);
CREATE UNIQUE INDEX `s1b` ON `x_d1` (`b`);
CREATE UNIQUE INDEX `s_xe` ON `x_d2_xe` (`parent_rsn`, `k`);
CREATE UNIQUE INDEX `s2a` ON `x_d2` (`x`);
CREATE UNIQUE INDEX `s2b` ON `x_d2` (`x`, `y`, `z_z1`, `z_z2`, `z_z3`);

-- Remaps: a second description of a record, which is a view
-- of the table the record is in.
CREATE OR REPLACE VIEW `r_e` AS
  SELECT `rsn`,
         `e1`
    FROM `d_e`
  ;
CREATE OR REPLACE VIEW `r_d` AS
  SELECT `rsn`,
         `d1`
    FROM `d`
  ;
CREATE OR REPLACE VIEW `r_g` AS
  SELECT `rsn`,
         `g1`,
         `g3`
    FROM `dmsii_globals`
  ;
CREATE OR REPLACE VIEW `r_xe` AS
  SELECT `rsn`,
         `k`
    FROM `x_d2_xe`
  ;
CREATE OR REPLACE VIEW `r_d2` AS
  SELECT `rsn`,
         `x` AS `p`,
         `y` AS `q`,
         `z_z1` AS `r1`,
         `z_z2` AS `r2`,
         `z_z3` AS `r3`
    FROM `x_d2`
  ;

-- Logical databases. Which structures a program may see is
-- a matter of grants rather than of shape, so what each one
-- names is written out here for whoever issues them.
--   LDB1:
--     D
--     RDS
--   LDB2:
--     R-D
--     RDS
--   LDB3:
--     EXDB
--     X-D1 through all of its sets
--     X-D2 through S2 = S2A
--   LDB4:
--     R-G
--     XD = R-D2 through S = S2B
--   LDB5:
--     X-D1
--     R-D2

