-- MariaDB schema for the Enterprise Database Server database 8-SUBSETS
-- Compiled from ../samples/8-subsets.dasdl by DASDL, generated by model2sql.
--
-- Every table carries `rsn`, a key of its own. DMSII addresses
-- a record by its physical address — the AAWORD, which encodes
-- the block and the offset within it — and a relational row
-- needs a key that does not move when the record does, for the
-- sets that reach it to point at something.
--
-- A set is an index over its data set; a subset is a table of
-- its own, because it holds entries for only some of the
-- records and an index cannot leave rows out. Reading whole
-- records through a subset is a join on `rsn`; reading only
-- its keys and DATA items — a FIND KEY OF — never leaves it.

CREATE DATABASE IF NOT EXISTS `8_subsets` DEFAULT CHARACTER SET utf8mb4;
USE `8_subsets`;

-- STUDENTS (data set)
CREATE TABLE IF NOT EXISTS `students` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(20),
  `gpa` DECIMAL(3,2) UNSIGNED,
  `major` CHAR(20),
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- BOOKS (compact data set)
CREATE TABLE IF NOT EXISTS `books` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` CHAR(20),
  `author` CHAR(20),
  `subject` CHAR(20),
  `checked_out` BOOLEAN,
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- EMPLOYEE (data set)
CREATE TABLE IF NOT EXISTS `employee` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_number` DECIMAL(7,0) UNSIGNED,
  `name` CHAR(20),
  `title` CHAR(18),
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- DEPT (data set)
CREATE TABLE IF NOT EXISTS `dept` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dept_no` DECIMAL(4,0) UNSIGNED,
  PRIMARY KEY (`rsn`)
) ENGINE=InnoDB;

-- POSTING (data set), embedded in DEPT
CREATE TABLE IF NOT EXISTS `dept_posting` (
  `rsn` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_rsn` BIGINT UNSIGNED NOT NULL,
  `line_no` DECIMAL(6,0) UNSIGNED,
  `amount` DECIMAL(11,2),
  `voided` BOOLEAN,
  PRIMARY KEY (`rsn`),
  KEY `dept_posting_parent` (`parent_rsn`),
  CONSTRAINT `dept_posting_owner` FOREIGN KEY (`parent_rsn`) REFERENCES `dept` (`rsn`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Sets and Accesses: an entry for every record of the data
-- set, which is what an index is.
CREATE UNIQUE INDEX `by_title` ON `books` (`title`);
CREATE INDEX `by_title_keydata` ON `books` (`title`, `author`);

-- Subsets: an entry for only some of the records, which an
-- index cannot be. Each is a table of its own, holding the
-- key items, the DATA items and the `rsn` of the record the
-- entry points at — so a FIND KEY OF is one lookup here and
-- never reaches the data set, which is what the key data
-- option exists for.
-- HONOR-ROLL: automatic subset of STUDENTS
--   holds the records where GPA GTR 3.5
CREATE TABLE IF NOT EXISTS `honor_roll` (
  `name` CHAR(20) NOT NULL,
  `rsn` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`name`, `rsn`),
  UNIQUE KEY `honor_roll_record` (`rsn`),
  CONSTRAINT `honor_roll_points_at` FOREIGN KEY (`rsn`) REFERENCES `students` (`rsn`) ON DELETE CASCADE
) ENGINE=InnoDB;
-- ENGLISH-MAJORS: automatic subset of STUDENTS
--   holds the records where MAJOR = "ENGLISH"
CREATE TABLE IF NOT EXISTS `english_majors` (
  `name` CHAR(20) NOT NULL,
  `rsn` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`name`, `rsn`),
  UNIQUE KEY `english_majors_record` (`rsn`),
  CONSTRAINT `english_majors_points_at` FOREIGN KEY (`rsn`) REFERENCES `students` (`rsn`) ON DELETE CASCADE
) ENGINE=InnoDB;
-- BY-AUTHOR: automatic subset of BOOKS
--   holds the records where NOT CHECKED-OUT
CREATE TABLE IF NOT EXISTS `by_author` (
  `author` CHAR(20) NOT NULL,
  `subject` CHAR(20),
  `title` CHAR(20),
  `rsn` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`author`, `rsn`),
  UNIQUE KEY `by_author_record` (`rsn`),
  CONSTRAINT `by_author_points_at` FOREIGN KEY (`rsn`) REFERENCES `books` (`rsn`) ON DELETE CASCADE
) ENGINE=InnoDB;
-- BY-SUBJECT: automatic subset of BOOKS
--   holds the records where NOT CHECKED-OUT
CREATE TABLE IF NOT EXISTS `by_subject` (
  `subject` CHAR(20) NOT NULL,
  `author` CHAR(20),
  `title` CHAR(20),
  `rsn` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`subject`, `rsn`),
  UNIQUE KEY `by_subject_record` (`rsn`),
  CONSTRAINT `by_subject_points_at` FOREIGN KEY (`rsn`) REFERENCES `books` (`rsn`) ON DELETE CASCADE
) ENGINE=InnoDB;
-- SUBORDINATE: manual subset of EMPLOYEE, ordered list
--   one per record of EMPLOYEE, which is where it is declared
--   the program decides what is in it: INSERT and REMOVE, not the server
CREATE TABLE IF NOT EXISTS `subordinate` (
  `owner_rsn` BIGINT UNSIGNED NOT NULL,
  `emp_number` DECIMAL(7,0) UNSIGNED NOT NULL,
  `rsn` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`owner_rsn`, `emp_number`),
  KEY `subordinate_record` (`rsn`),
  CONSTRAINT `subordinate_belongs_to` FOREIGN KEY (`owner_rsn`) REFERENCES `employee` (`rsn`) ON DELETE CASCADE,
  CONSTRAINT `subordinate_points_at` FOREIGN KEY (`rsn`) REFERENCES `employee` (`rsn`) ON DELETE CASCADE
) ENGINE=InnoDB;
--   a deleted record takes its entry with it; DMSII leaves the entry behind
-- OPEN-POSTINGS: automatic subset of POSTING
--   one per record of DEPT, which is where it is declared
--   holds the records where NOT VOIDED
CREATE TABLE IF NOT EXISTS `open_postings` (
  `parent_rsn` BIGINT UNSIGNED NOT NULL,
  `line_no` DECIMAL(6,0) UNSIGNED NOT NULL,
  `rsn` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`parent_rsn`, `line_no`, `rsn`),
  UNIQUE KEY `open_postings_record` (`rsn`),
  CONSTRAINT `open_postings_points_at` FOREIGN KEY (`rsn`) REFERENCES `dept_posting` (`rsn`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Keeping the automatic subsets current. DELIMITER is a
-- directive of the mariadb client, not a statement: it is
-- what lets a trigger body hold more than one statement.
DELIMITER $$
CREATE TRIGGER `honor_roll_on_store` AFTER INSERT ON `students` FOR EACH ROW
BEGIN
  IF NEW.`gpa` > 3.5 THEN
    INSERT INTO `honor_roll` (`name`, `rsn`) VALUES (NEW.`name`, NEW.`rsn`);
  END IF;
END$$
CREATE TRIGGER `honor_roll_on_modify` AFTER UPDATE ON `students` FOR EACH ROW
BEGIN
  DELETE FROM `honor_roll` WHERE `rsn` = OLD.`rsn`;
  IF NEW.`gpa` > 3.5 THEN
    INSERT INTO `honor_roll` (`name`, `rsn`) VALUES (NEW.`name`, NEW.`rsn`);
  END IF;
END$$
CREATE TRIGGER `english_majors_on_store` AFTER INSERT ON `students` FOR EACH ROW
BEGIN
  IF NEW.`major` = 'ENGLISH' THEN
    INSERT INTO `english_majors` (`name`, `rsn`) VALUES (NEW.`name`, NEW.`rsn`);
  END IF;
END$$
CREATE TRIGGER `english_majors_on_modify` AFTER UPDATE ON `students` FOR EACH ROW
BEGIN
  DELETE FROM `english_majors` WHERE `rsn` = OLD.`rsn`;
  IF NEW.`major` = 'ENGLISH' THEN
    INSERT INTO `english_majors` (`name`, `rsn`) VALUES (NEW.`name`, NEW.`rsn`);
  END IF;
END$$
CREATE TRIGGER `by_author_on_store` AFTER INSERT ON `books` FOR EACH ROW
BEGIN
  IF NOT NEW.`checked_out` THEN
    INSERT INTO `by_author` (`author`, `subject`, `title`, `rsn`) VALUES (NEW.`author`, NEW.`subject`, NEW.`title`, NEW.`rsn`);
  END IF;
END$$
CREATE TRIGGER `by_author_on_modify` AFTER UPDATE ON `books` FOR EACH ROW
BEGIN
  DELETE FROM `by_author` WHERE `rsn` = OLD.`rsn`;
  IF NOT NEW.`checked_out` THEN
    INSERT INTO `by_author` (`author`, `subject`, `title`, `rsn`) VALUES (NEW.`author`, NEW.`subject`, NEW.`title`, NEW.`rsn`);
  END IF;
END$$
CREATE TRIGGER `by_subject_on_store` AFTER INSERT ON `books` FOR EACH ROW
BEGIN
  IF NOT NEW.`checked_out` THEN
    INSERT INTO `by_subject` (`subject`, `author`, `title`, `rsn`) VALUES (NEW.`subject`, NEW.`author`, NEW.`title`, NEW.`rsn`);
  END IF;
END$$
CREATE TRIGGER `by_subject_on_modify` AFTER UPDATE ON `books` FOR EACH ROW
BEGIN
  DELETE FROM `by_subject` WHERE `rsn` = OLD.`rsn`;
  IF NOT NEW.`checked_out` THEN
    INSERT INTO `by_subject` (`subject`, `author`, `title`, `rsn`) VALUES (NEW.`subject`, NEW.`author`, NEW.`title`, NEW.`rsn`);
  END IF;
END$$
CREATE TRIGGER `open_postings_on_store` AFTER INSERT ON `dept_posting` FOR EACH ROW
BEGIN
  IF NOT NEW.`voided` THEN
    INSERT INTO `open_postings` (`parent_rsn`, `line_no`, `rsn`) VALUES (NEW.`parent_rsn`, NEW.`line_no`, NEW.`rsn`);
  END IF;
END$$
CREATE TRIGGER `open_postings_on_modify` AFTER UPDATE ON `dept_posting` FOR EACH ROW
BEGIN
  DELETE FROM `open_postings` WHERE `rsn` = OLD.`rsn`;
  IF NOT NEW.`voided` THEN
    INSERT INTO `open_postings` (`parent_rsn`, `line_no`, `rsn`) VALUES (NEW.`parent_rsn`, NEW.`line_no`, NEW.`rsn`);
  END IF;
END$$
DELIMITER ;

